# Verify that out-of-tree kernel modules are signed with the key this kernel
# trusts. VERIFIES — it does not sign. Read the next paragraph before changing
# that.
#
# ONE SIGNING AUTHORITY: KBUILD
# This distro builds every image with CONFIG_MODULE_SIG_FORCE=y and
# CONFIG_MODULE_SIG_ALL=y (security-prod.cfg via igw_security_prod, which is in
# the default IOTGW_KERNEL_FEATURES). Confirmed on target: sig_enforce=Y.
#
# CONFIG_MODULE_SIG_ALL makes Kbuild sign modules during `modules_install` —
# and that includes EXTERNAL modules, because an out-of-tree recipe's install
# step routes through Kbuild. Verified for dx-driver against its real Makefile:
#
#     modules/Makefile:74
#       install:
#               $(MAKE) -C $(KERNEL_DIR) M=$(MODULE_DIR) ... modules_install
#
# So the .ko is already signed by the time do_install finishes. An earlier
# version of this class signed it a SECOND time with sign-file. That was wrong:
# two signing authorities for one artifact, with no one owning the outcome.
# Kbuild is the authority; this class is the gate that proves Kbuild did its
# job, so a packaging change that silently bypasses modules_install fails the
# build instead of shipping an unloadable module.
#
# If a recipe ever installs .ko files WITHOUT going through modules_install,
# this class will fail it — correctly. The fix then is to route that recipe
# through modules_install, not to add a second signer here.
#
# USAGE
#   inherit iotgw-kernel-module-signing
#
# KEY PROVENANCE — STILL NOT PRODUCTION READY
# The kernel USED to sign with an autogenerated key ("signer: Build time
# autogenerated kernel key" on target), regenerated whenever
# certs/signing_key.pem was absent at kernel build time, so a module signed
# against build N would not load on a kernel from build N+1.
#
# That specific defect is now fixable: iotgw-kernel-module-sig-key.bbclass
# wires CONFIG_MODULE_SIG_KEY to a persistent operator-held key when
# IOTGW_MODULE_SIG_KEY_FILE is set (kas/local.yml). It is OPT-IN — with the
# variable unset the auto-generated-key behaviour above is still what you get,
# so read the running config before assuming which applies. Confirm on target
# with `modinfo -F signer <mod>`, which names the key.
#
# CORRECTION TO AN EARLIER VERSION OF THIS COMMENT: it claimed "RAUC already
# hard-fails on kernel/module mismatch". That is NOT reliably true, and the
# claim was inherited rather than checked. bundle-hooks-fit.sh does have a
# pairing guard, but it is FAIL-OPEN: expected_release is read from the
# bootfiles archive, and IOTGW_RAUC_UPDATE_BOOTFILES defaults to "0", so a
# rootfs-only bundle carries no archive, expected_release is empty, and the
# mismatch check silently passes.
#
# Before this is production-usable, all three were required. Status:
#   1. DONE (mechanism) — a persistent operator-held signing key via
#      CONFIG_MODULE_SIG_KEY, shaped like the FIT key in kas/local.yml. See
#      iotgw-kernel-module-sig-key.bbclass. The key currently in use is a
#      plain file on the build host with no hardware protection: right for a
#      lab image, NOT a production posture. Moving it into the FIT key's
#      HSM/YubiKey handling (docs/FIT_BOOT_SIGNING.md) is still outstanding.
#   2. OPEN — fail-closed kernel/module pairing: compare against the RUNNING
#      kernel when no bootfiles archive is present, or enforce full FIT
#      bundles for every update that moves modules.
#   3. ADDRESSED for the key-rotation case — iotgw-kernel-module-sig-key
#      registers the key file in do_configure[file-checksums], so changing the
#      key content changes the kernel's do_configure taskhash and, through the
#      dependency chain, every downstream module task. Without that, swapping
#      the key left every taskhash identical and sstate would return modules
#      signed by the retired key. Note this covers the KEY CHANGING; it is not
#      a general proof that every sstate object was produced by the current
#      key, and it has not yet been exercised by an actual rotation on target.

inherit module

IOTGW_MODULE_SIG_MAGIC ?= "~Module signature appended~"

do_install[vardeps] += "IOTGW_MODULE_SIG_MAGIC"

do_install:append() {
    iotgw_verify_kernel_module_signatures
}

iotgw_verify_kernel_module_signatures() {
    found=0
    unsigned=""
    for ko in $(find "${D}" -type f -name '*.ko'); do
        found=$(expr $found + 1)
        # A signed module ends with EXACTLY this 28-byte trailer
        # (27 chars + newline). Compare at the exact offset rather than
        # grepping a window near EOF: a substring search would also pass on a
        # module that merely CONTAINS the text somewhere in its tail, which
        # proves proximity, not a well-formed signature.
        if [ "$(tail -c 28 "$ko" | tr -d '\n')" != "${IOTGW_MODULE_SIG_MAGIC}" ]; then
            unsigned="$unsigned $ko"
        fi
    done

    if [ "$found" -eq 0 ]; then
        bbfatal "module signature check: no .ko files found under ${D}." \
                "Either the module did not build or its install path changed;" \
                "passing silently here would ship an unusable package."
    fi

    if [ -n "$unsigned" ]; then
        bbfatal "module signature check: UNSIGNED module(s):$unsigned" \
                "This kernel runs CONFIG_MODULE_SIG_FORCE=y, so these would" \
                "install correctly and then fail to load with ENOKEY." \
                "Expected Kbuild's CONFIG_MODULE_SIG_ALL to sign them during" \
                "modules_install — check that this recipe's install target" \
                "actually routes through modules_install."
    fi

    bbnote "module signature check: $found module(s) carry a signature trailer"
}
