# Persistent kernel module-signing key for the in-tree kernel build.
#
# WHY
# This distro sets CONFIG_MODULE_SIG_FORCE=y and CONFIG_MODULE_SIG_ALL=y
# (security-prod.cfg). With CONFIG_MODULE_SIG_KEY left at its default,
# certs/Makefile generates a fresh throwaway keypair whenever ${B}/certs is
# empty, and the resulting kernel trusts ONLY that key. Every kernel rebuild
# therefore invalidates every module built against the previous one:
#
#   modinfo -F signer <mod>  ->  "Build time autogenerated kernel key"
#
# which is why a rootfs-only RAUC bundle (kernel not updated, modules updated)
# produces a device that cannot load its own modules. Pointing
# CONFIG_MODULE_SIG_KEY at an operator-held key makes kernel and modules
# independently rebuildable.
#
# SCOPE — this is part 1 of 3. Parts 2 and 3 remain OPEN:
#   2. fail-closed kernel/module pairing in bundle-hooks-fit.sh (today the
#      guard is fail-open when no bootfiles archive is present);
#   3. an operator process for rotating and protecting this key. The dev key
#      generated by docs/KERNEL.md is a FILE ON THE BUILD HOST with no
#      hardware protection -- adequate for lab images, NOT for production.
#      A production key belongs in the same HSM/YubiKey posture as the FIT
#      signing key (docs/FIT_BOOT_SIGNING.md).
# Do not describe module signing as production-ready on the strength of this
# class alone.
#
# OPT-IN, not mandatory. Unlike FIT signing (which is hard-guarded because
# there is no unsigned boot flow), leaving IOTGW_MODULE_SIG_KEY_FILE unset is
# a supported configuration: the build keeps today's auto-generated-key
# behaviour so a fresh clone still builds without operator key material.
IOTGW_MODULE_SIG_KEY_FILE ?= ""

# Kbuild reads the key from this path, relative to the kernel objtree (${B}).
# Must match module-signing-key.cfg; asserted below rather than assumed.
IOTGW_MODULE_SIG_KEY_DEST ?= "certs/iotgw-module-signing-key.pem"

# Fragment carrying CONFIG_MODULE_SIG_KEY. Appended parse-time; the fragments
# class derives SRC_URI from IOTGW_KERNEL_FRAGMENTS at expansion time, so the
# inherit order of the two classes does not matter.
IOTGW_KERNEL_FRAGMENTS += "${@'module-signing-key.cfg' if d.getVar('IOTGW_MODULE_SIG_KEY_FILE') else ''}"

# Rebuild when the key CONTENT changes, not just its path.
#
# Without this, swapping the key on disk leaves every taskhash identical and
# bitbake happily restores a kernel -- and out-of-tree modules signed against
# the RETIRED key -- from sstate. That is failure mode 3 in
# iotgw-kernel-module-signing.bbclass, and it is silent: the image builds
# clean and the modules refuse to load on the target.
#
# do_configure's hash feeds every downstream task, so this propagates to
# do_compile/do_install here and, through the shared kernel workdir, to
# out-of-tree module recipes.
do_configure[file-checksums] += "${@'%s:True' % d.getVar('IOTGW_MODULE_SIG_KEY_FILE') if d.getVar('IOTGW_MODULE_SIG_KEY_FILE') else ''}"
do_configure[vardeps] += "IOTGW_MODULE_SIG_KEY_FILE IOTGW_MODULE_SIG_KEY_DEST"

python () {
    keyfile = d.getVar('IOTGW_MODULE_SIG_KEY_FILE')
    if not keyfile:
        return
    import os
    # Require an absolute path. The parse-time check below resolves a relative
    # value against bitbake's CWD while the do_configure shell check resolves it
    # against the task's, so a relative value could pass one and fail the other.
    if not os.path.isabs(keyfile):
        bb.fatal("IOTGW_MODULE_SIG_KEY_FILE must be an absolute path, got '%s'. "
                 "A relative path resolves differently at parse time and at "
                 "do_configure time." % keyfile)
    if not os.path.isfile(keyfile):
        bb.fatal("IOTGW_MODULE_SIG_KEY_FILE is set to '%s', which does not exist. "
                 "Generate it per docs/KERNEL.md (\"Persistent module-signing key\") "
                 "or unset the variable to fall back to Kbuild's auto-generated key."
                 % keyfile)
}

iotgw_install_module_sig_key() {
    [ -n "${IOTGW_MODULE_SIG_KEY_FILE}" ] || return 0

    src="${IOTGW_MODULE_SIG_KEY_FILE}"
    dest="${B}/${IOTGW_MODULE_SIG_KEY_DEST}"

    if [ ! -r "$src" ]; then
        bbfatal "iotgw-module-sig-key: cannot read ${IOTGW_MODULE_SIG_KEY_FILE}"
    fi

    # Kbuild's sign-file wants ONE PEM holding both halves: it reads the
    # private key from CONFIG_MODULE_SIG_KEY and extracts the certificate from
    # the same file into certs/signing_key.x509 (certs/Makefile, extract-cert).
    # A cert-only or key-only PEM fails deep inside do_compile with a much less
    # obvious error, so check here.
    if ! grep -q 'BEGIN.*PRIVATE KEY' "$src"; then
        bbfatal "iotgw-module-sig-key: $src contains no private key -- it must hold BOTH the private key and its certificate"
    fi
    if ! grep -q 'BEGIN CERTIFICATE' "$src"; then
        bbfatal "iotgw-module-sig-key: $src contains no certificate -- it must hold BOTH the private key and its certificate"
    fi

    install -d "$(dirname "$dest")"
    install -m 0600 "$src" "$dest"

    # Silent-failure guard. If the fragment did not reach .config (renamed,
    # dropped from IOTGW_KERNEL_FRAGMENTS, or overridden by a later merge),
    # Kbuild falls back to certs/signing_key.pem and AUTO-GENERATES a key --
    # the build succeeds and the persistent key is quietly ignored, which is
    # exactly the bug this class exists to remove.
    if ! grep -q "^CONFIG_MODULE_SIG_KEY=\"${IOTGW_MODULE_SIG_KEY_DEST}\"$" "${B}/.config"; then
        bbfatal "iotgw-module-sig-key: installed the key at ${IOTGW_MODULE_SIG_KEY_DEST} but .config does not select it. Expected CONFIG_MODULE_SIG_KEY=\"${IOTGW_MODULE_SIG_KEY_DEST}\"; got: $(grep '^CONFIG_MODULE_SIG_KEY=' "${B}/.config" || echo '<unset>')"
    fi

    bbnote "iotgw-module-sig-key: using persistent signing key from ${IOTGW_MODULE_SIG_KEY_FILE}"
}

# Runs after iotgw-kernel-fragments' own do_configure:append, so .config has
# already been merged and olddefconfig'd by the time the assertion above reads
# it. That ordering is why the check can be a hard failure rather than a hint.
do_configure[postfuncs] += "iotgw_install_module_sig_key"

# Publish the key to the shared kernel dir, or OUT-OF-TREE MODULES GO UNSIGNED.
#
# This is not optional plumbing — without it the build produces unsigned
# dx-driver modules and Kbuild does not complain. kernel.bbclass:554-558
# populates STAGING_KERNEL_BUILDDIR for external module builds with a
# HARDCODED GLOB:
#
#     if [ -e certs/signing_key.x509 ]; then
#             mkdir -p $kerneldir/certs
#             cp certs/signing_key.* $kerneldir/certs/
#     fi
#
# `signing_key.*` matches the DEFAULT key name and nothing else. Our key is
# deliberately named differently (see module-signing-key.cfg for why), so the
# certificate reached the shared dir and the private key did not. An external
# module build then ran scripts/sign-file against a missing key.
#
# And that failure is SILENT. scripts/Makefile.modinst:108-109:
#
#     # Don't stop modules_install even if we can't sign external modules.
#     cmd_sign = ... $(if $(KBUILD_EXTMOD),|| true)
#
# Kbuild swallows the error for out-of-tree modules, so modules_install
# "succeeds" and emits unsigned .ko files that install fine and then fail to
# load with EKEYREJECTED under CONFIG_MODULE_SIG_FORCE=y. Only
# iotgw-kernel-module-signing.bbclass' verification gate catches it — which it
# did, on the first build after this class was introduced.
#
# Exposure note: this puts a PRIVATE KEY in
# ${STAGING_KERNEL_BUILDDIR}/certs/. That is not a new posture — the glob
# above already copied the auto-generated `signing_key.pem`, private half
# included, to exactly the same place. It is one more reason the dev key is
# not a production key.
do_shared_workdir:append() {
    [ -n "${IOTGW_MODULE_SIG_KEY_FILE}" ] || return 0

    src="${B}/${IOTGW_MODULE_SIG_KEY_DEST}"
    if [ ! -f "$src" ]; then
        bbfatal "iotgw-module-sig-key: $src is missing at do_shared_workdir -- do_configure should have installed it"
    fi

    install -d "${STAGING_KERNEL_BUILDDIR}/certs"
    install -m 0600 "$src" "${STAGING_KERNEL_BUILDDIR}/${IOTGW_MODULE_SIG_KEY_DEST}"

    # The certificate half must be there too, or sign-file has nothing to
    # embed. kernel.bbclass' glob does copy signing_key.x509 (extract-cert
    # writes it under that fixed name regardless of CONFIG_MODULE_SIG_KEY), but
    # assert it rather than trust it -- if it ever stops being copied, the
    # symptom is silently unsigned modules again.
    if [ ! -f "${STAGING_KERNEL_BUILDDIR}/certs/signing_key.x509" ]; then
        bbfatal "iotgw-module-sig-key: certs/signing_key.x509 absent from ${STAGING_KERNEL_BUILDDIR} -- external modules would be signed with no certificate"
    fi

    bbnote "iotgw-module-sig-key: published signing key to ${STAGING_KERNEL_BUILDDIR}/${IOTGW_MODULE_SIG_KEY_DEST}"
}
