#!/bin/bash
# DEEPX DX-M1 accelerator acceptance check for the IoT Gateway distro (iotgw).
#
# Runs ON the gateway after flashing a `make dev-deepx` image and produces
# evidence from the board rather than from build metadata: module identity and
# signature, autoload, PCIe binding, device-node policy, daemon identity,
# SELinux denials, and a real inference run with a CPU-fallback discriminator.
#
# Why identity comes first: the kernel module-signing key is AUTOGENERATED per
# kernel build, so a DX-M1 module only loads on the kernel built beside it. A
# full-flash image carries a matched pair. If `uname -r` does not equal the
# module's vermagic, the wrong image is on the card and every later result is
# meaningless — section 0 stops the run there.
#
# Usage:
#   # On target directly:
#   sudo ./dxm1-acceptance-target.sh
#
#   # From host over SSH (no copy needed):
#   ssh <gw> 'sudo bash -s' < scripts/deepx/dxm1-acceptance-target.sh
#
#   # Via the aggregating runner (not in the default set — name it):
#   scripts/run-target-checks.sh <gw> deepx-acceptance
#
# Environment:
#   IOTGW_DXM1_EXPECT_VERMAGIC  Kernel release string the flashed image was
#                               built with. When set, section 0 asserts the
#                               board is running THAT build — a real oracle.
#                               Unset, section 0 can only prove the kernel and
#                               the module agree with each other, which a
#                               stale-but-self-consistent card also passes.
#                               Derive it on the host from the artifact:
#                                 basename $(ls -d build/tmp/work/*/dx-driver/*/package/usr/lib/modules/*/ | tail -1)
#   IOTGW_DXM1_EXPECT_SIG_KEY   Expected module signing-key fingerprint
#                               (`modinfo ... sig_key`). Same rationale.
#
#                               DERIVE IT FROM THE SHIPPED ARTIFACT, NOT THE
#                               BUILD TREE. The kernel's signing key is
#                               autogenerated per kernel build, and
#                               build/tmp/work-shared/<machine>/kernel-build-artifacts/
#                               certs/signing_key.x509 is regenerated whenever a
#                               kernel task re-runs — while the modules actually
#                               packaged may have come from sstate and been
#                               signed by the PREVIOUS key. Reading the cert
#                               there then reports a mismatch against a
#                               perfectly good image. Read the module you
#                               actually shipped:
#
#                                 tar -I zstd -xf <image>.rootfs.tar.zst -C /tmp/m \
#                                     --wildcards --no-anchored 'dx_dma.ko*'
#                                 modinfo -F sig_key /tmp/m/usr/lib/modules/*/updates/pci_deepx/dx_dma.ko
#
#                               Corroborating signal, and the reason a mismatch
#                               here is never the whole story: with
#                               sig_enforce=Y a module signed by a retired key
#                               CANNOT load at all. If section 1 shows both
#                               modules loaded and no signature rejections in
#                               dmesg, the kernel and modules on the board are a
#                               matched pair regardless of what this variable
#                               was set to.
#   IOTGW_DXM1_MODEL            .dxnn model for the inference run
#                               (default /etc/dx-stream-sample/YoloV5S_PPU.dxnn)
#   IOTGW_DXM1_RUN_SECONDS      Inference duration (default 10)
#   IOTGW_DXM1_SKIP_INFERENCE=1 Skip section 7 (device checks only)
#
# Exit status: 0 if no check FAILed. SELinux denials are reported as FINDINGs
# and do not change the exit code — on first contact they define the policy
# work rather than proving the integration wrong.
#
# Pairs with:
#   scripts/ota/ota-smoke-target.sh — post-OTA / BSP smoke

set -u
PASS=0
FAIL=0
SKIP=0
FINDING=0

say_pass()    { printf '  \e[32mPASS\e[0m %s\n' "$1"; PASS=$((PASS+1)); }
say_fail()    { printf '  \e[31mFAIL\e[0m %s\n' "$1"; FAIL=$((FAIL+1)); }
say_skip()    { printf '  \e[33mSKIP\e[0m %s — %s\n' "$1" "${2:-}"; SKIP=$((SKIP+1)); }
say_finding() { printf '  \e[35mFIND\e[0m %s\n' "$1"; FINDING=$((FINDING+1)); }
say_info()    { printf '       %s\n' "$1"; }
section()     { printf '\n== %s ==\n' "$1"; }

# Record raw output as evidence. Claims in a commit body have to be
# reproducible from this transcript, not believed.
evidence() {
    local label="$1"; shift
    printf '  --- %s: %s\n' "$label" "$*"
    "$@" 2>&1 | sed 's/^/      /'
}

# dxtop reads its terminal description from /etc/terminfo, which the vendor's
# /etc/profile.d/dxrt_env.sh exports. A piped `bash -s` is not a login shell,
# so nothing sources that file — set it here or dxtop renders nothing.
export TERMINFO="${TERMINFO:-/etc/terminfo}"
# dxtop also needs TERM. Over `ssh 'bash -s'` there is no tty, so TERM is unset
# and ncurses dies with "Error opening terminal: unknown." — the sampler then
# silently yields zero samples and the CPU-fallback check degrades to a SKIP.
# `linux` is chosen because /etc/terminfo actually ships it (alacritty, ansi,
# dumb, linux, rxvt); xterm is NOT present.
# Set unconditionally, NOT as ${TERM:-linux}: over `ssh 'bash -s'` TERM is
# already set to the literal string "unknown", which is non-empty, so a default
# expansion keeps it and ncurses still dies. Observed 2026-09-01.
export TERM=linux
export PATH="$PATH:/usr/bin:/usr/sbin"

MODEL="${IOTGW_DXM1_MODEL:-/etc/dx-stream-sample/YoloV5S_PPU.dxnn}"
RUN_SECONDS="${IOTGW_DXM1_RUN_SECONDS:-10}"

# Set by section 3. Defaults to "unsafe" so that a section-3 failure, or any
# path that skips it, can never fall through into touching the device.
DX_DECODE_OK=0

summary_and_exit() {
    printf '\nSummary: PASS=%d FAIL=%d SKIP=%d FINDING=%d\n' \
        "$PASS" "$FAIL" "$SKIP" "$FINDING"
    [ "$FINDING" -gt 0 ] && printf 'FINDINGs are recorded, not failures — see section 6.\n'
    [ "$FAIL" -eq 0 ]
    exit $?
}

# Everything below runs inside main() for one specific reason: see FIX 1 note
# above summary_and_exit. Do not un-wrap it.
main() {

# ---------------------------------------------------------------------------
section "Preflight — is the DX-M1 stack installed at all"
if ! modinfo dx_dma >/dev/null 2>&1 && [ ! -e /dev/dxrt0 ]; then
    say_skip "DX-M1 stack" "dx_dma module not installed (IOTGW_ENABLE_DEEPX_DXM1 off, or wrong image)"
    summary_and_exit
fi
say_pass "dx_dma module present in this rootfs"

# ---------------------------------------------------------------------------
section "0. Identity — the whole demo rests on this"
KREL=$(uname -r)
MOD_VERMAGIC=$(modinfo -F vermagic dx_dma 2>/dev/null | awk '{print $1}')
MOD_SIGNER=$(modinfo -F signer dx_dma 2>/dev/null)
MOD_SIGKEY=$(modinfo -F sig_key dx_dma 2>/dev/null)
say_info "uname -r        : ${KREL}"
say_info "dx_dma vermagic : ${MOD_VERMAGIC:-<none>}"
say_info "dx_dma signer   : ${MOD_SIGNER:-<none>}"
say_info "dx_dma sig_key  : ${MOD_SIGKEY:-<none>}"

if [ -z "$MOD_VERMAGIC" ]; then
    say_fail "dx_dma vermagic readable"
elif [ "$KREL" = "$MOD_VERMAGIC" ]; then
    say_pass "running kernel == dx_dma vermagic (matched pair)"
else
    say_fail "running kernel != dx_dma vermagic — WRONG IMAGE ON THE CARD"
    say_info "STOP. Do not interpret later failures; reflash and re-run."
    summary_and_exit
fi

if [ -n "${IOTGW_DXM1_EXPECT_VERMAGIC:-}" ]; then
    if [ "$KREL" = "$IOTGW_DXM1_EXPECT_VERMAGIC" ]; then
        say_pass "running kernel == the build we flashed (${IOTGW_DXM1_EXPECT_VERMAGIC})"
    else
        say_fail "running kernel is NOT the build we flashed (expected ${IOTGW_DXM1_EXPECT_VERMAGIC})"
    fi
else
    say_skip "board runs the build we flashed" \
        "IOTGW_DXM1_EXPECT_VERMAGIC unset; kernel/module self-consistency alone cannot detect a stale card"
fi

if [ -n "${IOTGW_DXM1_EXPECT_SIG_KEY:-}" ]; then
    if [ "$MOD_SIGKEY" = "$IOTGW_DXM1_EXPECT_SIG_KEY" ]; then
        say_pass "module signed by the expected key"
    else
        say_fail "module sig_key differs from expected (sstate may have returned a module signed by a retired key)"
    fi
fi

# ---------------------------------------------------------------------------
section "1. Signature accepted by the running kernel"
SIG_ENFORCE=$(cat /sys/module/module/parameters/sig_enforce 2>/dev/null)
say_info "sig_enforce     : ${SIG_ENFORCE:-<unreadable>}"
if [ "$SIG_ENFORCE" = "Y" ]; then
    say_pass "sig_enforce=Y (unsigned modules cannot load)"
else
    say_fail "sig_enforce is not Y — loading proves nothing about signatures"
fi

for m in dx_dma dxrt_driver; do
    if lsmod | awk '{print $1}' | grep -qx "$m"; then
        say_pass "$m loaded"
    else
        say_fail "$m NOT loaded"
    fi
done
evidence "lsmod (dx)" sh -c "lsmod | grep -E '^(dx_dma|dxrt_driver)' || echo '(none loaded)'"

# Match what the kernel ACTUALLY prints, not the errno name. kernel/module/
# signing.c maps the failure to a reason string and emits
#   pr_notice("Loading of %s is rejected\n", reason)
# with reason one of: "unsigned module", "module with unsupported crypto",
# "module with unavailable key". The string "ENOKEY" never appears in dmesg —
# and note that under sig_enforce=Y the errno returned to userspace is
# EKEYREJECTED, not ENOKEY (ENOKEY is only the internal verification result).
#
# The old pattern grepped for 'ENOKEY' and 'Loading of unsigned module', so a
# module signed by a RETIRED key — "module with unavailable key", precisely the
# failure this distro's autogenerated per-build key makes likely — matched
# nothing and this check passed. Silent false pass; fixed 2026-09-01.
SIGERR=$(dmesg 2>/dev/null | grep -iE 'Loading of .* is rejected|module verification failed|EKEYREJECTED|signature.*(fail|invalid)' | head -5)
if [ -z "$SIGERR" ]; then
    say_pass "no module-signature rejections in dmesg"
else
    say_fail "signature errors in dmesg"
    printf '%s\n' "$SIGERR" | sed 's/^/      /'
fi
evidence "dmesg (dx)" sh -c "dmesg 2>/dev/null | grep -iE 'dx_dma|dxrt|deepx' | tail -20 || echo '(no dx lines)'"

# ---------------------------------------------------------------------------
section "2. Autoload and load order"
MODULES_LOAD_STATE=$(systemctl show systemd-modules-load.service -p ActiveState --value 2>/dev/null)
MODULES_LOAD_RC=$(systemctl show systemd-modules-load.service -p ExecMainStatus --value 2>/dev/null)
say_info "systemd-modules-load: ${MODULES_LOAD_STATE:-?} (exit ${MODULES_LOAD_RC:-?})"
if [ "$MODULES_LOAD_RC" = "0" ]; then
    say_pass "systemd-modules-load.service completed cleanly"
else
    say_fail "systemd-modules-load.service did not exit 0"
    evidence "modules-load status" systemctl status --no-pager -l systemd-modules-load.service
fi

# A forced modules-load.d entry is now a DEFECT, not the design. Proven on
# hardware 2026-09-01: CONFIG_PCIE_BRCMSTB=m (inherited from the mainline arm64
# defconfig) means the BCM2712 host bridge is itself a module, loading at
# ~4.70s. A forced entry fired dx_dma at ~3.11s — 1.5s BEFORE the bus existed —
# so dxrt_driver counted 0 devices and never rescanned. Removing the entry lets
# udev autoload dx_dma by PCI modalias at enumeration time, which is what makes
# a stock Debian install work.
AUTOLOAD=$(cat /etc/modules-load.d/*.conf /usr/lib/modules-load.d/*.conf 2>/dev/null | grep -E '^\s*dx' | sort -u)
if [ -z "$AUTOLOAD" ]; then
    say_pass "no forced modules-load entry — dx_dma is autoloaded by PCI modalias after enumeration"
else
    say_fail "dx_dma is force-loaded via modules-load.d ('$AUTOLOAD') — races the PCIe host bridge"
fi

# The outcome that actually matters, and the one that was silently wrong before:
# dxrt_driver enumerates ONCE at module init and never rescans, so it must run
# after dx_dma has probed the endpoint.
CDEV=$(dmesg 2>/dev/null | grep -a 'dxrt_driver_cdev_init' | tail -1)
say_info "${CDEV:-<no dxrt_driver_cdev_init line in dmesg>}"
CDEV_N=$(printf '%s' "$CDEV" | grep -oE '[0-9]+ devices' | grep -oE '^[0-9]+')
if [ -n "$CDEV_N" ] && [ "$CDEV_N" -ge 1 ] 2>/dev/null; then
    say_pass "dxrt_driver enumerated $CDEV_N device(s) — it initialised after the endpoint existed"
else
    say_fail "dxrt_driver enumerated 0 devices — it ran before dx_dma probed the endpoint"
fi
evidence "load timeline" sh -c "dmesg 2>/dev/null | grep -aE 'brcm-pcie.*link up|dx_dma: loading|enabling device|Probe Done|cdev_init' | head -8" 

# Recorded, not asserted. dxrt_driver declares `depends: dx_dma` while dx_dma
# ships `softdep dx_dma pre: dxrt_driver`, so modprobe must resolve the hard
# symbol dependency first: the observable order is dx_dma then dxrt_driver, not
# the reverse. Asserting "dxrt_driver first" would encode a contradiction. What
# matters, and is asserted above, is that both end up loaded with no manual step.
evidence "modprobe --show-depends dx_dma" modprobe --show-depends dx_dma
evidence "softdep" sh -c "grep -rh 'softdep' /etc/modprobe.d /usr/lib/modprobe.d 2>/dev/null | grep dx || echo '(none)'"

# ---------------------------------------------------------------------------
section "3. Driver actually bound to the device"
# Discover the slot from the driver's own binding rather than a hardcoded BDF:
# the DX-M1 sat at 0001:01:00.0 on this board, but the binding is the fact.
DXSLOT=""
DXDRV=""
for d in /sys/bus/pci/devices/*; do
    [ "$(cat "$d/vendor" 2>/dev/null)" = "0x1ff4" ] || continue
    DXSLOT=$(basename "$d")
    # The module is dx_dma; the pci_driver it registers is named dx_dma_pcie.
    # Reading the device's own driver symlink avoids depending on either.
    [ -e "$d/driver" ] && DXDRV=$(basename "$(readlink -f "$d/driver")")
    break
done
if [ -n "$DXDRV" ]; then
    say_pass "PCI device $DXSLOT bound to driver '$DXDRV'"
elif [ -n "$DXSLOT" ]; then
    say_fail "DEEPX device present at $DXSLOT but NO driver bound"
    # DEEPX vendor id 1ff4 (from the module's own PCI aliases) — is the card even seen?
    evidence "lspci -d 1ff4:" sh -c "lspci -nn -d 1ff4: || echo '(no 1ff4 device enumerated)'"
    DXSLOT=$(lspci -n -d 1ff4: 2>/dev/null | awk '{print $1}' | head -1)
fi

if [ -n "$DXSLOT" ]; then
    evidence "lspci -nnk -s $DXSLOT" lspci -nnk -s "$DXSLOT"
    LSPCI_VV=$(lspci -vv -s "$DXSLOT" 2>/dev/null)
    # DX_DECODE_OK gates section 7. Touching a BAR whose decoding is off is not
    # a failed read — it is an unclaimed PCIe transaction, which on this SoC
    # raises a fatal SError and panics the kernel. Observed 2026-09-01.
    DX_DECODE_OK=1
    if printf '%s' "$LSPCI_VV" | grep -q 'Control:.*Mem+'; then
        say_pass "Memory Space decoding enabled (Mem+)"
    else
        say_fail "Mem- — BAR decoding DISABLED; MMIO to this device panics the kernel"
        DX_DECODE_OK=0
    fi
    if printf '%s' "$LSPCI_VV" | grep -q 'BusMaster+'; then
        say_pass "BusMaster+ (driver enabled DMA)"
    else
        say_fail "BusMaster- — DMA not enabled; device cannot do useful work"
        DX_DECODE_OK=0
    fi
    if printf '%s' "$LSPCI_VV" | grep -q 'Region 0:.*\[disabled\]'; then
        say_fail "BAR0 still [disabled]"
        DX_DECODE_OK=0
    else
        say_pass "BARs no longer [disabled]"
    fi
    # Link state: recorded, not asserted. Gen2 x1 is the expected baseline on a
    # Pi 5 — the external FFC connector is fed by a 1-lane controller, and
    # dtparam=pciex1_gen=3 is NOT set in this image, so 5GT/s is correct here.
    say_info "link: $(printf '%s' "$LSPCI_VV" | grep -oE 'LnkSta:.*' | head -1)"
    printf '  --- AER counters:\n'
    printf '%s\n' "$LSPCI_VV" | grep -E 'UESta|CESta|LaneErrStat' | sed 's/^/      /' \
        || printf '      (none reported)\n'
fi

# ---------------------------------------------------------------------------
section "4. Device node policy"
NODES=$(ls -1 /dev/dxrt* 2>/dev/null)
if [ -z "$NODES" ]; then
    say_fail "no /dev/dxrt* device node"
else
    for n in $NODES; do
        OWNER=$(stat -c '%U %G %a' "$n" 2>/dev/null)
        say_info "$n: $OWNER"
        if [ "$OWNER" = "root dxrt 660" ]; then
            say_pass "$n is root:dxrt 0660 (not upstream's world-writable 0666)"
        else
            say_fail "$n is '$OWNER' — expected 'root dxrt 660'"
        fi
    done
    # The SELinux label is recorded whatever it is: an unconfined default is
    # itself the finding that defines the policy work, not a failure here.
    evidence "ls -lZ /dev/dxrt*" sh -c "ls -lZ /dev/dxrt* 2>/dev/null || ls -l /dev/dxrt*"
fi
if id dxrt >/dev/null 2>&1; then
    say_pass "dxrt service account exists ($(id dxrt))"
    SHELL_DXRT=$(getent passwd dxrt | cut -d: -f7)
    case "$SHELL_DXRT" in
        */nologin|*/false) say_pass "dxrt is non-interactive ($SHELL_DXRT)" ;;
        *)                 say_fail "dxrt has an interactive shell ($SHELL_DXRT)" ;;
    esac
else
    say_fail "dxrt service account missing"
fi

# ---------------------------------------------------------------------------
section "5. Daemon"
if ! systemctl cat dxrtd.service >/dev/null 2>&1; then
    say_fail "dxrtd.service not installed"
else
    ENABLED=$(systemctl is-enabled dxrtd.service 2>/dev/null)
    ACTIVE=$(systemctl is-active dxrtd.service 2>/dev/null)
    say_info "is-enabled=$ENABLED  is-active=$ACTIVE"
    if [ "$ENABLED" = "enabled" ]; then say_pass "dxrtd.service enabled"
    else say_fail "dxrtd.service not enabled ($ENABLED)"; fi
    if [ "$ACTIVE" = "active" ]; then say_pass "dxrtd.service active"
    else say_fail "dxrtd.service not active ($ACTIVE)"; fi
    # Identity is the point of the unit: it must be the dxrt account, not root.
    # If it is root, User= was overridden or the daemon re-execs — investigate
    # rather than accept.
    DXRTD_USER=$(ps -o user= -C dxrtd 2>/dev/null | head -1 | tr -d ' ')
    if [ -z "$DXRTD_USER" ]; then
        say_fail "no running dxrtd process"
    elif [ "$DXRTD_USER" = "dxrt" ]; then
        say_pass "dxrtd runs as dxrt (unprivileged; device access via group)"
    else
        say_fail "dxrtd runs as '$DXRTD_USER', expected dxrt"
    fi
    evidence "dxrtd status" systemctl status --no-pager -l -n 20 dxrtd.service
fi

# ---------------------------------------------------------------------------
section "6. SELinux denials (findings, not failures)"
if [ ! -d /sys/fs/selinux ]; then
    say_skip "SELinux denials" "SELinux not enabled in this kernel"
else
    say_info "enforce=$(cat /sys/fs/selinux/enforce 2>/dev/null)  $(getenforce 2>/dev/null)"
    DENIALS=$(journalctl -b --no-pager 2>/dev/null | grep -i 'avc:.*denied' | grep -iE 'dxrt|dx_dma|deepx')
    if [ -z "$DENIALS" ]; then
        say_pass "no AVC denials involving dxrtd or the device"
    else
        say_finding "AVC denials involving the DX-M1 stack — record verbatim, feed into policy work"
        printf '%s\n' "$DENIALS" | sed 's/^/      /'
    fi
    evidence "ausearch -m avc -ts boot (tail)" sh -c "ausearch -m avc -ts boot 2>/dev/null | tail -20 || echo '(ausearch: no matches or unavailable)'"
fi

# ---------------------------------------------------------------------------
section "7. Real inference on the NPU"
if [ "$DX_DECODE_OK" != "1" ]; then
    say_skip "inference" \
        "REFUSING to touch the device: BAR decoding/bus-mastering is off. MMIO in this state raises a fatal SError and panics the kernel (observed 2026-09-01, Comm: dxrtd). Fix section 3 first."
elif [ "${IOTGW_DXM1_SKIP_INFERENCE:-0}" = "1" ]; then
    say_skip "inference" "IOTGW_DXM1_SKIP_INFERENCE=1"
elif ! command -v run_model >/dev/null 2>&1; then
    say_skip "inference" "run_model not installed"
elif [ ! -r "$MODEL" ]; then
    say_skip "inference" "model not found: $MODEL"
else
    # a. The runtime's own view of the device.
    if command -v dxrt-cli >/dev/null 2>&1; then
        # timeout is not optional: an unguarded dxrt-cli against a device in a
        # bad state hangs forever and takes the whole run with it (seen 2026-09-01).
        DXSTATUS=$(timeout 30 dxrt-cli -s 2>&1)
        printf '  --- dxrt-cli -s:\n'; printf '%s\n' "$DXSTATUS" | sed 's/^/      /'
        if printf '%s' "$DXSTATUS" | grep -qiE 'npu|device.*[0-9]|dx[_-]?m1'; then
            say_pass "dxrt-cli reports a device"
        else
            say_fail "dxrt-cli -s does not report a device"
        fi
        evidence "dxrt-cli --errorstat" sh -c "timeout 30 dxrt-cli --errorstat 2>&1 || true"
    else
        say_skip "dxrt-cli device status" "dxrt-cli not installed"
    fi

    # c. NPU utilisation sampled DURING the run — the CPU-fallback
    # discriminator. A demo that silently falls back to CPU still prints
    # plausible detections and a plausible FPS; non-zero NPU utilisation is
    # the one signal a fallback path cannot produce. dxtop is a TUI, so it
    # needs a PTY: `script` provides one.
    DXTOP_LOG=""
    DXTOP_PID=""
    if command -v dxtop >/dev/null 2>&1 && command -v script >/dev/null 2>&1; then
        DXTOP_LOG=$(mktemp /tmp/dxtop.XXXXXX.log)
        script -q -c 'stty rows 50 cols 200 2>/dev/null; exec dxtop' "$DXTOP_LOG" \
            >/dev/null 2>&1 </dev/null &
        DXTOP_PID=$!
        sleep 2
    else
        say_skip "NPU utilisation sampling" "dxtop or script(1) not installed"
    fi

    # b. The inference run itself.
    RUN_LOG=$(mktemp /tmp/run_model.XXXXXX.log)
    printf '  --- run_model -m %s -t %s\n' "$MODEL" "$RUN_SECONDS"
    if timeout $((RUN_SECONDS + 180)) run_model -m "$MODEL" -t "$RUN_SECONDS" \
            >"$RUN_LOG" 2>&1; then
        say_pass "run_model completed"
    else
        say_fail "run_model failed or timed out (exit $?)"
    fi
    tail -30 "$RUN_LOG" | sed 's/^/      /'

    FPS=$(grep -oE 'FPS[[:space:]]*:[[:space:]]*[0-9.]+' "$RUN_LOG" | grep -oE '[0-9.]+$' | tail -1)
    if [ -n "$FPS" ] && [ "${FPS%%.*}" -gt 0 ] 2>/dev/null; then
        say_pass "inference throughput reported: ${FPS} FPS"
    else
        say_fail "no positive FPS in run_model output"
    fi

    # Stop the sampler by PID. Never `pkill -f dxtop` here: the pattern would
    # match this script's own command line.
    if [ -n "$DXTOP_PID" ]; then
        kill -TERM "$DXTOP_PID" 2>/dev/null
        sleep 1
        pgrep -x dxtop >/dev/null 2>&1 && pkill -x dxtop 2>/dev/null
        wait "$DXTOP_PID" 2>/dev/null

        # dxtop frames look like: "Core : 0 ... Util: 37.5% ... Clock: 1000 MHz"
        # `strings` strips the PTY's ANSI and control bytes.
        # dxtop is a TUI: it positions values with ANSI cursor moves, so "Core : 0"
        # and its "Util: NN%" are NOT on the same line of the capture. Strip the
        # escapes and collapse the ENTIRE stream to one line before matching —
        # the same approach the vendor's own parser takes. A per-line regex
        # silently matches nothing, which reads as "no samples" rather than a bug.
        DXFLAT=$(strings "$DXTOP_LOG" 2>/dev/null \
            | sed -e 's/\[[0-9;?]*[A-Za-z]//g' | tr '\n' ' ' | tr -s ' ')
        MAXUTIL=$(printf '%s' "$DXFLAT" \
            | grep -oE 'Util: [0-9.]+' | grep -oE '[0-9.]+' | sort -g | tail -1)
        SAMPLES=$(printf '%s' "$DXFLAT" | grep -oE 'Util: [0-9.]+' | wc -l)
        say_info "dxtop: ${SAMPLES:-0} utilisation samples, peak ${MAXUTIL:-n/a}%"
        if [ -n "$MAXUTIL" ] && [ "$(printf '%s' "$MAXUTIL" | cut -d. -f1)" -gt 0 ] 2>/dev/null; then
            say_pass "NPU utilisation was non-zero during inference — it ran on DX-M1, not a CPU fallback"
        elif [ "${SAMPLES:-0}" = "0" ]; then
            say_skip "CPU-fallback discriminator" "dxtop produced no parseable samples; run 'dxtop' interactively during a run instead"
        else
            say_fail "NPU utilisation stayed at 0 during inference — suspect a CPU fallback"
        fi
        # Echo the samples into the transcript rather than only pointing at the
        # files: sshd hardening gives this session a PrivateTmp, so /tmp paths
        # named here are gone the moment the connection closes.
        printf '  --- dxtop utilisation samples (parsed):\n'
        printf '%s' "$DXFLAT" | grep -oE 'Core : [0-9]+ Util: [0-9.]+ *%?' \
            | tail -12 | sed 's/^/      /'
        say_info "raw logs this session only: $DXTOP_LOG  $RUN_LOG"
    fi

    # The vendor sample's run.sh is a GStreamer/dx-stream pipeline
    # (dxpreprocess ! dxinfer ! dxpostprocess ! dxosd ! waylandsink).
    #
    # Whether it can run is a property of the IMAGE, not of this script: the
    # headless dev image ships none of that stack, the desktop/lab image ships
    # all of it. This used to be an UNCONDITIONAL say_skip with the reason
    # hardcoded to "none are in this image" — so on an image that could in fact
    # run the pipeline it still reported a skip, and the one check that
    # exercises the full decode -> NPU -> compositor path silently never ran.
    # Detect, do not assume.
    #
    # run_model above proves the NPU works. It does NOT prove the GStreamer
    # elements, the postprocess library or the display path work; only this does.
    SAMPLE_RUN="/etc/dx-stream-sample/run.sh"
    PIPE_SECONDS="${PIPE_SECONDS:-20}"
    GST_MISSING=""
    command -v gst-launch-1.0 >/dev/null 2>&1 || GST_MISSING="gst-launch-1.0"
    if [ -z "$GST_MISSING" ]; then
        for _el in dxpreprocess dxinfer dxpostprocess dxosd waylandsink; do
            gst-inspect-1.0 "$_el" >/dev/null 2>&1 </dev/null \
                || GST_MISSING="$GST_MISSING $_el"
        done
    fi

    # waylandsink is a CLIENT: a compositor must already be running. Find a live
    # wayland socket rather than trusting $WAYLAND_DISPLAY, which is unset in a
    # non-login ssh session like this one.
    WL_DIR=""; WL_SOCK=""
    for _d in "${XDG_RUNTIME_DIR:-}" /run/weston /run/user/0 /run/user/1000; do
        [ -n "$_d" ] && [ -d "$_d" ] || continue
        for _s in "$_d"/wayland-*; do
            [ -S "$_s" ] || continue
            case "$_s" in *.lock) continue ;; esac
            WL_DIR="$_d"; WL_SOCK="${_s##*/}"; break 2
        done
    done

    if [ ! -x "$SAMPLE_RUN" ]; then
        say_skip "$SAMPLE_RUN" "not installed in this image"
    elif [ -n "$GST_MISSING" ]; then
        say_skip "$SAMPLE_RUN" "missing:${GST_MISSING} (expected on the headless image; the desktop/lab image ships these)"
    elif [ -z "$WL_DIR" ]; then
        say_skip "$SAMPLE_RUN" "no running Wayland compositor — no wayland-* socket in XDG_RUNTIME_DIR, /run/weston or /run/user/*"
    else
        PIPE_LOG=$(mktemp /tmp/dxstream_run.XXXXXX.log)
        printf '  --- %s (%ss, display %s/%s)\n' "$SAMPLE_RUN" "$PIPE_SECONDS" "$WL_DIR" "$WL_SOCK"
        # cd first: run.sh passes model-path=./YoloV5S_PPU.dxnn, relative to its
        # own directory. </dev/null on the pipeline is not optional — this whole
        # script is commonly fed to `ssh <gw> 'sudo bash -s' < script`, and any
        # child that reads stdin eats the REST OF THE SCRIPT. That has already
        # caused a run with real failures to print "ALL PASSED".
        ( cd "$(dirname "$SAMPLE_RUN")" \
          && XDG_RUNTIME_DIR="$WL_DIR" WAYLAND_DISPLAY="$WL_SOCK" \
             timeout "$PIPE_SECONDS" "./$(basename "$SAMPLE_RUN")" ) \
            >"$PIPE_LOG" 2>&1 </dev/null
        _rc=$?
        # A healthy pipeline is still playing when timeout kills it, so exit 124
        # is the EXPECTED outcome; reaching PLAYING without an ERROR is the real
        # signal. Exit 0 also passes (short clip that ran to EOS).
        if grep -q "Setting pipeline to PLAYING" "$PIPE_LOG" \
           && ! grep -qE "^ERROR|Erroneous pipeline|not-negotiated|no element" "$PIPE_LOG"; then
            say_pass "run.sh reached PLAYING — H.264 decode -> dx elements -> compositor negotiated end to end"
        else
            say_fail "run.sh pipeline did not reach PLAYING (exit $_rc)"
        fi
        tail -15 "$PIPE_LOG" | sed 's/^/      /'
        rm -f "$PIPE_LOG"
    fi
fi

# ---------------------------------------------------------------------------
section "8. Persistence across reboot"
say_info "Not automated in a single pass. Reboot the board and re-run this"
say_info "script: identical results with no manual intervention is what"
say_info "separates 'we got it working' from 'it works'."
say_info "  systemctl reboot   # then re-run"

summary_and_exit
}

# </dev/null is load-bearing, not decoration — see the note on main() above.
main </dev/null
