# Port meta-deepx-m1's dx-driver from its walnascar baseline to wrynose.
#
# The recipe sets S = "${WORKDIR}/git/modules". Up to and including walnascar
# that worked because base.bbclass moved unpacked sources into WORKDIR as a
# compatibility step. wrynose oe-core removed that shim (commit 53e9ea30aaf,
# "base.bbclass: drop compatibility moving of sources into workdir"), whose
# commit message states the author deliberately made it "a hard qa error"
# rather than a warning. Sources now land in UNPACKDIR:
#
#   UNPACKDIR ??= "${WORKDIR}/sources"     (meta/conf/bitbake.conf)
#   S          = "${UNPACKDIR}/${BP}"
#
# wrynose also changed where the git fetcher puts things: destsuffix now
# follows the new S default, so the checkout lands at ${UNPACKDIR}/${BP}
# (dx-driver-2.6.0/), NOT ${UNPACKDIR}/git. Confirmed by running do_unpack and
# looking, after an earlier guess of ${UNPACKDIR}/git/modules drew:
#   "the directory ... pointed to by the S variable doesn't exist"
# Actual layout: sources/dx-driver-2.6.0/{LICENSE,modules/Makefile}
S = "${UNPACKDIR}/${BP}/modules"

# LIC_FILES_CHKSUM is "file://../LICENSE", resolved relative to S, so it
# follows S to ${UNPACKDIR}/${BP}/LICENSE. Left untouched deliberately —
# restating it here would silently decouple our copy from upstream's checksum
# if they ever rotate the licence file.

# Module signing. This distro builds every image with
# CONFIG_MODULE_SIG_FORCE=y (igw_security_prod is in the default
# IOTGW_KERNEL_FEATURES), confirmed on target as sig_enforce=Y. Upstream
# dx-driver has no signing step, so without this its .ko would install
# correctly and then fail to load with ENOKEY.
#
# Kbuild is the signer, not us: this recipe's install target routes through
# `modules_install` (modules/Makefile:74) and the kernel sets
# CONFIG_MODULE_SIG_ALL=y, so the .ko is signed there. The class VERIFIES that
# happened and fails the build if any .ko lacks a signature trailer — an
# earlier draft signed a second time, which meant two authorities for one
# artifact. Read the class header: the kernel's key is AUTOGENERATED, so module
# and kernel are only valid as a matched pair from the same build.
inherit iotgw-kernel-module-signing

# TRIM_UNUSED_KSYMS: resolved. The 2026-08-31 build failed at modpost with
# get_user_pages_fast and sched_set_normal undefined; both are EXPORT_SYMBOL_GPL
# in-tree but were trimmed out of Module.symvers. Fixed surgically via
# CONFIG_UNUSED_KSYMS_WHITELIST (fragments/deepx-dxm1-ksyms.cfg +
# files/deepx-dxm1-ksyms.txt), gated on igw_deepx_dxm1 so other images keep
# trimming at full strength. Requires IOTGW_ENABLE_DEEPX_DXM1=1.

# Tighten the NPU device node. Upstream installs:
#     KERNEL=="dxrt*", MODE="0666"
# i.e. world read/write on an accelerator device, on an image that otherwise
# runs SELinux and the full security-prod.cfg posture. That is a default worth
# refusing rather than inheriting.
#
# This is a deny-by-default PLACEHOLDER, not the final answer. The real answer
# is a dedicated group whose only member is the consuming service, plus an
# SELinux label — but the group has to be created by whichever recipe owns the
# consumer, and cross-recipe group membership in this layer goes through
# IOTGW_ROOTFS_SUPPLEMENTARY_GROUPS (see .claude/rules/yocto-patterns.md), not
# through USERADD_PARAM. That decision belongs with the recipe that actually
# uses the accelerator, which does not exist yet.
#
# Until then root-only is correct: nothing consumes the device, so nothing
# regresses, and the permissive default cannot reach an image by accident. A
# consumer arriving later will fail loudly on permissions, which is the right
# way to be reminded to make the decision.
do_install:append() {
    install -d ${D}${sysconfdir}/udev/rules.d
    echo 'KERNEL=="dxrt*", MODE="0660", OWNER="root", GROUP="root"' \
        > ${D}${sysconfdir}/udev/rules.d/99-dx-dma.rules
}

# buildpaths QA: strip the recorded GCC command line from debug info.
#
# do_package_qa failed with the .ko "contains reference to TMPDIR". The
# references are NOT source paths — DEBUG_PREFIX_MAP already handles those.
# They are the absolute paths of this distro's GCC hardening plugins:
#
#   .../work-shared/raspberrypi5/kernel-build-artifacts/scripts/gcc-plugins/
#       latent_entropy_plugin.so
#       stackleak_plugin.so
#
# 15 occurrences, all in .debug_str; .comment, .modinfo and .rodata are clean.
# They arrive because CONFIG_GCC_PLUGINS / GCC_PLUGIN_LATENT_ENTROPY /
# KSTACK_ERASE (security-prod.cfg) make the kernel pass -fplugin=<abs path>,
# and GCC's default -grecord-gcc-switches writes that command line into DWARF.
#
# So this distro's own hardening options are what leak the build path into a
# shipped binary. INSANE_SKIP would hide that rather than fix it, and this
# project explicitly does not ship host paths in artifacts — so drop the
# recorded switches instead. Cost is small and bounded: debuggers lose the
# "what flags built this" note; line tables, symbols and types are untouched.
KCFLAGS:append = " -gno-record-gcc-switches"
EXTRA_OEMAKE:append = " KCFLAGS='${KCFLAGS}'"
