# Port meta-deepx-m1's dx-driver from its walnascar baseline to wrynose.
#
# The recipe sets S = "${WORKDIR}/git/modules". Up to and including walnascar
# that worked because base.bbclass moved unpacked sources into WORKDIR as a
# compatibility step. wrynose oe-core removed that shim (commit 53e9ea30aaf,
# "base.bbclass: drop compatibility moving of sources into workdir"), whose
# commit message states the author deliberately made it "a hard qa error"
# rather than a warning. Sources now land in UNPACKDIR:
#
#   UNPACKDIR ??= "${WORKDIR}/sources"     (meta/conf/bitbake.conf)
#   S          = "${UNPACKDIR}/${BP}"
#
# wrynose also changed where the git fetcher puts things: destsuffix now
# follows the new S default, so the checkout lands at ${UNPACKDIR}/${BP}
# (dx-driver-2.6.0/), NOT ${UNPACKDIR}/git. Confirmed by running do_unpack and
# looking, after an earlier guess of ${UNPACKDIR}/git/modules drew:
#   "the directory ... pointed to by the S variable doesn't exist"
# Actual layout: sources/dx-driver-2.6.0/{LICENSE,modules/Makefile}
S = "${UNPACKDIR}/${BP}/modules"

# LIC_FILES_CHKSUM is "file://../LICENSE", resolved relative to S, so it
# follows S to ${UNPACKDIR}/${BP}/LICENSE. Left untouched deliberately —
# restating it here would silently decouple our copy from upstream's checksum
# if they ever rotate the licence file.

# Module signing. This distro builds every image with
# CONFIG_MODULE_SIG_FORCE=y (igw_security_prod is in the default
# IOTGW_KERNEL_FEATURES), confirmed on target as sig_enforce=Y. Upstream
# dx-driver has no signing step, so without this its .ko would install
# correctly and then fail to load with ENOKEY.
#
# Kbuild is the signer, not us: this recipe's install target routes through
# `modules_install` (modules/Makefile:74) and the kernel sets
# CONFIG_MODULE_SIG_ALL=y, so the .ko is signed there. The class VERIFIES that
# happened and fails the build if any .ko lacks a signature trailer — an
# earlier draft signed a second time, which meant two authorities for one
# artifact. Read the class header: the kernel's key is AUTOGENERATED, so module
# and kernel are only valid as a matched pair from the same build.
inherit iotgw-kernel-module-signing

# TRIM_UNUSED_KSYMS: resolved. The 2026-08-31 build failed at modpost with
# get_user_pages_fast and sched_set_normal undefined; both are EXPORT_SYMBOL_GPL
# in-tree but were trimmed out of Module.symvers. Fixed surgically via
# CONFIG_UNUSED_KSYMS_WHITELIST (fragments/deepx-dxm1-ksyms.cfg +
# files/deepx-dxm1-ksyms.txt), gated on igw_deepx_dxm1 so other images keep
# trimming at full strength. Requires IOTGW_ENABLE_DEEPX_DXM1=1.

# Device policy moved OUT of this bbappend. The 0660 root:root placeholder
# that lived here is superseded by iotgw-deepx-runtime, which owns the whole
# story coherently: it creates the dxrt service account and group, ships the
# udev rule as root:dxrt 0660, and runs dxrtd under that identity. Splitting
# the rule from the account that makes it meaningful was the wrong seam.
#
# Upstream's own do_install still writes MODE="0666" to
# ${sysconfdir}/udev/rules.d/99-dx-dma.rules, so it is DELETED from this
# package below. An earlier version of this comment claimed our identically
# named file would simply "win" because it comes from a higher-priority layer.
# That is false: layer priority decides which RECIPE provides a file, not which
# PACKAGE may own a path at install time. Two packages owning one path is a
# hard RPM conflict, and do_rootfs failed with exactly that:
#
#   file /etc/udev/rules.d/99-dx-dma.rules conflicts between attempted
#   installs of iotgw-deepx-runtime and dx-driver
#
# Deleting it here leaves iotgw-deepx-runtime as the single owner, which also
# means the 0666 rule is not merely overridden but never shipped at all.

# Autoload the PCIe driver at boot. dx_dma is the only module named here on
# purpose: the driver ships "softdep dx_dma pre: dxrt_driver" in dx_dma.conf,
# so modprobe pulls dxrt_driver in FIRST. Listing both would be redundant and
# would risk loading them in the wrong order.
KERNEL_MODULE_AUTOLOAD += "dx_dma"

# Make the recipe's own package pull the modules it built.
#
# kernel-module-split names out-of-tree module packages
# kernel-module-<name>-${KERNEL_VERSION} and emits NO versionless RPROVIDES —
# confirmed from pkgdata, which carries no RPROVIDES key at all. So an image
# cannot depend on "kernel-module-dx-dma"; do_rootfs fails with
# "nothing provides kernel-module-dx-dma".
#
# Hard-coding the versioned name in a packagegroup would bake the kernel
# version into an unrelated recipe and rot at the next kernel bump. Instead the
# dx-driver package — which IS produced, and which a consumer can name stably —
# depends on its own modules, with ${KERNEL_VERSION} expanded here where it is
# legitimately in scope.
#
# The repo's usual "kernel-modules" idiom does not help: that meta-package
# covers modules built by the KERNEL recipe, not out-of-tree ones from a
# separate recipe.
RDEPENDS:${PN} += " \
    kernel-module-dx-dma-${KERNEL_VERSION} \
    kernel-module-dxrt-driver-${KERNEL_VERSION} \
"

# buildpaths QA: strip the recorded GCC command line from debug info.
#
# do_package_qa fails with the .ko "contains reference to TMPDIR". The
# references are NOT source paths — DEBUG_PREFIX_MAP handles those. They are
# the absolute paths of this distro's own GCC hardening plugins:
#
#   .../kernel-build-artifacts/scripts/gcc-plugins/latent_entropy_plugin.so
#   .../kernel-build-artifacts/scripts/gcc-plugins/stackleak_plugin.so
#
# 15 occurrences, all in .debug_str; .comment/.modinfo/.rodata are clean.
# CONFIG_GCC_PLUGINS / GCC_PLUGIN_LATENT_ENTROPY / KSTACK_ERASE
# (security-prod.cfg) make the kernel pass -fplugin=<abs path>, and GCC's
# default -grecord-gcc-switches writes that command line into DWARF. So this
# distro's own hardening options leak the build path into a shipped binary.
#
# INSANE_SKIP would hide that rather than fix it, and this project does not
# ship host paths in artifacts. Cost of the fix is bounded: debuggers lose the
# "what flags built this" note; line tables, symbols and types are untouched.
#
# Affects ANY out-of-tree module built against this kernel, not just DX-M1.
KCFLAGS:append = " -gno-record-gcc-switches"
EXTRA_OEMAKE:append = " KCFLAGS='${KCFLAGS}'"

# Remove upstream's world-writable udev rule from this package. Device policy
# belongs to iotgw-deepx-runtime, which owns the dxrt account and group that
# make a 0660 node meaningful.
do_install:append() {
    rm -f ${D}${sysconfdir}/udev/rules.d/99-dx-dma.rules
    # Clean up BOTH now-empty directories, innermost first. Removing only
    # rules.d leaves an empty /etc/udev, which do_package rejects as
    # "installed but not shipped in any package" — an empty directory still
    # counts as installed content.
    rmdir --ignore-fail-on-non-empty \
        ${D}${sysconfdir}/udev/rules.d \
        ${D}${sysconfdir}/udev 2>/dev/null || true
}

FILES:${PN}:remove = "${sysconfdir}/udev/rules.d/99-dx-dma.rules"
