# --- Version pin: the upstream recipe's is wrong ---------------------------
#
# meta-deepx-m1 ships this recipe as dx-driver_2.6.0.bb, but its
# SRCREV c05be168ea0c28757737035ea58aab6e59f03256 is the commit tagged
# "v2.4.1" (2026-04-17). The module built from it reports MODULE_VERSION
# 2.2.0. Three version numbers, none of which agree, and the tree is three
# releases behind main.
#
# Repinned to the real v2.6.0 tip. This is not a routine bump — the older tree
# is missing code that directly concerns this board:
#
#   * dx_link_health.c — PCIe link-health monitoring and auto-recovery, keyed
#     on config-read status, Vendor ID != 0xFFFF, the DLLLA (Data Link Layer
#     Link Active) bit, and negotiated speed/width. Our 2026-08-31 PCIe
#     baseline recorded DLActive- while LnkSta still reported a speed and
#     width, i.e. exactly the state this code exists to detect.
#   * An MMIO guard, `mmio_safe = link_state == DX_LINK_UP && ret ==
#     PCIBIOS_SUCCESSFUL && (command & PCI_COMMAND_MEMORY)`. On 2026-09-01
#     the old driver reached "Probe Done!!" with Mem- and BusMaster- clear
#     and BARs disabled; the runtime's first MMIO was an unclaimed PCIe
#     transaction and the board took a fatal SError. Comm: dxrtd, UID 992.
#   * RPI_BUILD — see the CONFIG_RPI_BUILD block below.
#   * softdep changed from `pre:` to `post:` — see the autoload block below.
#
# Upstream file size for the PCIe driver alone: 773 lines at the old pin,
# 1229 at v2.6.0.
SRCREV = "7074748e7104f470b02f517583abba652b3f05fa"

# LIC_FILES_CHKSUM is unchanged across the bump — LICENSE still md5
# df0ebe3edba67d21cb2e798ef0ee2905, verified against the v2.6.0 tree, so the
# recipe's existing checksum stays correct and is deliberately not restated.

# --- wrynose source-layout port -------------------------------------------
# Port meta-deepx-m1's dx-driver from its walnascar baseline to wrynose.
#
# The recipe sets S = "${WORKDIR}/git/modules". Up to and including walnascar
# that worked because base.bbclass moved unpacked sources into WORKDIR as a
# compatibility step. wrynose oe-core removed that shim (commit 53e9ea30aaf,
# "base.bbclass: drop compatibility moving of sources into workdir"), whose
# commit message states the author deliberately made it "a hard qa error"
# rather than a warning. Sources now land in UNPACKDIR:
#
#   UNPACKDIR ??= "${WORKDIR}/sources"     (meta/conf/bitbake.conf)
#   S          = "${UNPACKDIR}/${BP}"
#
# wrynose also changed where the git fetcher puts things: destsuffix now
# follows the new S default, so the checkout lands at ${UNPACKDIR}/${BP}
# (dx-driver-2.6.0/), NOT ${UNPACKDIR}/git. Confirmed by running do_unpack and
# looking, after an earlier guess of ${UNPACKDIR}/git/modules drew:
#   "the directory ... pointed to by the S variable doesn't exist"
# Actual layout: sources/dx-driver-2.6.0/{LICENSE,modules/Makefile}
S = "${UNPACKDIR}/${BP}/modules"

# LIC_FILES_CHKSUM is "file://../LICENSE", resolved relative to S, so it
# follows S to ${UNPACKDIR}/${BP}/LICENSE. Left untouched deliberately —
# restating it here would silently decouple our copy from upstream's checksum
# if they ever rotate the licence file.

# Module signing. This distro builds every image with
# CONFIG_MODULE_SIG_FORCE=y (igw_security_prod is in the default
# IOTGW_KERNEL_FEATURES), confirmed on target as sig_enforce=Y. Upstream
# dx-driver has no signing step, so without this its .ko would install
# correctly and then fail to load with ENOKEY.
#
# Kbuild is the signer, not us: this recipe's install target routes through
# `modules_install` (modules/Makefile:74) and the kernel sets
# CONFIG_MODULE_SIG_ALL=y, so the .ko is signed there. The class VERIFIES that
# happened and fails the build if any .ko lacks a signature trailer — an
# earlier draft signed a second time, which meant two authorities for one
# artifact. Read the class header: the kernel's key is AUTOGENERATED, so module
# and kernel are only valid as a matched pair from the same build.
inherit iotgw-kernel-module-signing

# TRIM_UNUSED_KSYMS: resolved. The 2026-08-31 build failed at modpost with
# get_user_pages_fast and sched_set_normal undefined; both are EXPORT_SYMBOL_GPL
# in-tree but were trimmed out of Module.symvers. Fixed surgically via
# CONFIG_UNUSED_KSYMS_WHITELIST (fragments/deepx-dxm1-ksyms.cfg +
# files/deepx-dxm1-ksyms.txt), gated on igw_deepx_dxm1 so other images keep
# trimming at full strength. Requires IOTGW_ENABLE_DEEPX_DXM1=1.

# Device policy moved OUT of this bbappend. The 0660 root:root placeholder
# that lived here is superseded by iotgw-deepx-runtime, which owns the whole
# story coherently: it creates the dxrt service account and group, ships the
# udev rule as root:dxrt 0660, and runs dxrtd under that identity. Splitting
# the rule from the account that makes it meaningful was the wrong seam.
#
# Upstream's own do_install still writes MODE="0666" to
# ${sysconfdir}/udev/rules.d/99-dx-dma.rules, so it is DELETED from this
# package below. An earlier version of this comment claimed our identically
# named file would simply "win" because it comes from a higher-priority layer.
# That is false: layer priority decides which RECIPE provides a file, not which
# PACKAGE may own a path at install time. Two packages owning one path is a
# hard RPM conflict, and do_rootfs failed with exactly that:
#
#   file /etc/udev/rules.d/99-dx-dma.rules conflicts between attempted
#   installs of iotgw-deepx-runtime and dx-driver
#
# Deleting it here leaves iotgw-deepx-runtime as the single owner, which also
# means the 0666 rule is not merely overridden but never shipped at all.

# --- DO NOT re-add KERNEL_MODULE_AUTOLOAD ----------------------------------
#
# There is deliberately NO `KERNEL_MODULE_AUTOLOAD += "dx_dma"` here. It looks
# like an omission; it is not. Adding it back reintroduces a boot-time race
# that ends in a kernel panic loop.
#
# Why. `KERNEL_MODULE_AUTOLOAD` writes /usr/lib/modules-load.d/dx_dma.conf, and
# systemd-modules-load modprobes it unconditionally and early. But this kernel
# inherits CONFIG_PCIE_BRCMSTB=m from the mainline arm64 defconfig, so the
# BCM2712 host bridge is ITSELF a module and does not load until later.
# Measured on hardware 2026-09-01:
#
#   [3.116199] dx_dma: loading out-of-tree module        <- forced, too early
#   [3.161570] dxrt_driver_cdev_init: 0 devices          <- nothing to find
#   [4.701316] brcm-pcie 1000110000.pcie: host bridge... <- bus appears, +1.5s
#   [4.832296] dx_dma_pcie 0001:01:00.0: enabling device <- endpoint probed
#
# dxrt_driver enumerates devices ONCE at module init and never rescans, so it
# counted zero, no /dev/dxrt* was created, and dxrtd never started. The vendor's
# `softdep dx_dma post: dxrt_driver` cannot help: it orders the two modules
# relative to each other, and says nothing about whether a PCI bus exists yet.
#
# Without the forced entry, udev autoloads dx_dma from the module's own PCI
# aliases (pci:v00001FF4d*) when the endpoint is enumerated — i.e. at exactly
# the right moment — and the softdep then pulls dxrt_driver in behind it:
#
#   [4.818551] brcm-pcie: link up, 5.0 GT/s PCIe x1
#   [5.210973] dx_dma: loading out-of-tree module        <- AFTER the bus
#   [5.316246] [dx_dma_pcie_probe] Probe Done!!
#   [5.424444] dxrt_driver_cdev_init: 1 devices          <- correct
#
# This is also why a stock Debian/DKMS install works: it ships no
# modules-load.d entry and relies on the same modalias path.
#
# Setting CONFIG_PCIE_BRCMSTB=y would also fix the ordering, and is arguably
# the better setting for fixed appliance hardware — but it is not required,
# costs a full kernel rebuild, and modalias ordering is what was validated.

# Make the recipe's own package pull the modules it built.
#
# kernel-module-split names out-of-tree module packages
# kernel-module-<name>-${KERNEL_VERSION} and emits NO versionless RPROVIDES —
# confirmed from pkgdata, which carries no RPROVIDES key at all. So an image
# cannot depend on "kernel-module-dx-dma"; do_rootfs fails with
# "nothing provides kernel-module-dx-dma".
#
# Hard-coding the versioned name in a packagegroup would bake the kernel
# version into an unrelated recipe and rot at the next kernel bump. Instead the
# dx-driver package — which IS produced, and which a consumer can name stably —
# depends on its own modules, with ${KERNEL_VERSION} expanded here where it is
# legitimately in scope.
#
# The repo's usual "kernel-modules" idiom does not help: that meta-package
# covers modules built by the KERNEL recipe, not out-of-tree ones from a
# separate recipe.
RDEPENDS:${PN} += " \
    kernel-module-dx-dma-${KERNEL_VERSION} \
    kernel-module-dxrt-driver-${KERNEL_VERSION} \
"

# --- Raspberry Pi build path ----------------------------------------------
#
# v2.6.0 carries BCM2712-specific code behind RPI_BUILD, but upstream gates it
# on a path substring test that CANNOT match a Yocto build
# (modules/Makefile:15):
#
#     ifneq ($(findstring rpi,$(KERNEL_DIR)),)
#     export CONFIG_RPI_BUILD=1
#
# Our KERNEL_DIR is ${STAGING_KERNEL_BUILDDIR}, whose path component is
# "raspberrypi5" — which does not contain the substring "rpi" (…r-r-y-p-i…).
# So the Pi path silently compiles OUT and the failure is invisible: a module
# that builds, installs and loads, minus the code written for this SoC.
#
# What it enables, from the source comment at dw-edma-pcie.c:
#   "BCM2712 (RPi CM5) brcmstb MSI controller allocates MSI vectors with
#    unaligned base data (e.g. data=0xc with MME=3 gives base=8, not 0xc).
#    The EP RTL generates data=(base & ~mask)|vector per PCI spec, but the
#    host expects data=base+vector — mismatch silently drops NPU done MSIs.
#    Force single MSI: all events muxed via SRAM SW IRQ block (dx_sw_irq)."
#
# Set explicitly rather than by faking the path. Passed as a make variable so
# it reaches pci_deepx/Kbuild's `ifneq ($(CONFIG_RPI_BUILD),)` through
# MAKEFLAGS. NOT a kernel Kconfig symbol despite the CONFIG_ prefix — it is
# upstream's own build flag, so it cannot collide with Kconfig.
#
# VERIFY, do not assume: the single-MSI log string must be present in the
# built object, otherwise this silently did nothing —
#   ${TARGET_PREFIX}strings dx_dma.ko | grep 'forcing single MSI'
EXTRA_OEMAKE:append = " CONFIG_RPI_BUILD=1"

# buildpaths QA: strip the recorded GCC command line from debug info.
#
# do_package_qa fails with the .ko "contains reference to TMPDIR". The
# references are NOT source paths — DEBUG_PREFIX_MAP handles those. They are
# the absolute paths of this distro's own GCC hardening plugins:
#
#   .../kernel-build-artifacts/scripts/gcc-plugins/latent_entropy_plugin.so
#   .../kernel-build-artifacts/scripts/gcc-plugins/stackleak_plugin.so
#
# 15 occurrences, all in .debug_str; .comment/.modinfo/.rodata are clean.
# CONFIG_GCC_PLUGINS / GCC_PLUGIN_LATENT_ENTROPY / KSTACK_ERASE
# (security-prod.cfg) make the kernel pass -fplugin=<abs path>, and GCC's
# default -grecord-gcc-switches writes that command line into DWARF. So this
# distro's own hardening options leak the build path into a shipped binary.
#
# INSANE_SKIP would hide that rather than fix it, and this project does not
# ship host paths in artifacts. Cost of the fix is bounded: debuggers lose the
# "what flags built this" note; line tables, symbols and types are untouched.
#
# Affects ANY out-of-tree module built against this kernel, not just DX-M1.
KCFLAGS:append = " -gno-record-gcc-switches"
EXTRA_OEMAKE:append = " KCFLAGS='${KCFLAGS}'"

# Remove upstream's world-writable udev rule from this package. Device policy
# belongs to iotgw-deepx-runtime, which owns the dxrt account and group that
# make a 0660 node meaningful.
do_install:append() {
    rm -f ${D}${sysconfdir}/udev/rules.d/99-dx-dma.rules
    # Clean up BOTH now-empty directories, innermost first. Removing only
    # rules.d leaves an empty /etc/udev, which do_package rejects as
    # "installed but not shipped in any package" — an empty directory still
    # counts as installed content.
    rmdir --ignore-fail-on-non-empty \
        ${D}${sysconfdir}/udev/rules.d \
        ${D}${sysconfdir}/udev 2>/dev/null || true
}

FILES:${PN}:remove = "${sysconfdir}/udev/rules.d/99-dx-dma.rules"
